server:
  port: 8081

spring:
  application:
    name: config-employee-roster-service
  profiles:
    active: dev

---
spring:
  profiles: dev
  data:
    mongodb:
      username: ${MONGODB_USER_NAME}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE_NAME}
      uri: mongodb+srv://${MONGODB_USER_NAME}:${MONGODB_PASSWORD}@cluster0-ww0df.mongodb.net/${MONGODB_DATABASE_NAME}?retryWrites=true&w=majority
      repositories:
        type: auto
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
