server:
  port: 8083
spring:
  application:
    name: edge-server
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  profiles: dev